### ISSUE TITLE
Maven Vue.js Template does not work because of webpack.config.js

### ISSUE THREAD

**Issue by lzhuor** [pmlopes/vertx-starter#14]
Hi, it seems the Vue components are using `vue-property-decorator` which requires type-script?

I'm getting this error using the template: 

```
ERROR in ./~/babel-loader/lib!./src/main/js/components/app/app.js
    Module build failed: SyntaxError: Unexpected token (4:0)
    
      2 | import { Component } from 'vue-property-decorator';
      3 | 
    > 4 | @Component({
        | ^
      5 |   components: {
      6 |     MenuComponent: require('../navmenu/navmenu.vue.html')
      7 |   }
    
     @ ./src/main/js/components/app/app.vue.html 3:2-36
     @ ./src/main/js/boot.js
```

**Comment by lzhuor** [comment]
Fixed by creating a `.babelrc` file under root. 

```javascript
{
  "presets": ["stage-2"],
  "plugins": ["transform-decorators-legacy"]
}
```

**Comment by pmlopes** [comment]
Is this issue related to the template or your code?

**Comment by lzhuor** [comment]
Hi @pmlopes , thank you for taking a look. I think this is related to the template. 

For example, in _/src/main/js/components/app/app.js_, `@Component` is a ES7 decorator which is not supported in babel-loader by default. After adding  `"plugins": ["transform-decorators-legacy"]` in a _.babelrc_ , the app works perfectly.

**Comment by pmlopes** [comment]
I have a .babel file in the template I need to check if I didn’t pick a wrong one from other project.

**Comment by pmlopes** [comment]
I just generated a vue project and it contains a .babelrc with the required plugins, I think you might have some issues with the dot file in the zip

**Comment by lzhuor** [comment]
Thank you for finding it! It seems I don't have that file while unzipping it.

```
~/Downloads/net_promoter_score_collector 2 is 📦  v0.0.1-SNAPSHOT via ⬢ v6.11.0 
•100% ➜ ls
mvnw                     pom.xml                  webpack.config.vendor.js
mvnw.cmd                 src
package.json  
```

**Comment by lzhuor** [comment]
OK, problem found. Somehow the dot files are hidden after unzipping them. It's not a problem from the project. Thank you for hints.

```
~/Downloads/net_promoter_score_collector 2 is 📦  v0.0.1-SNAPSHOT via ⬢ v6.11.0 
•100% ➜ la
total 88
-rw-rw-r--@ 1 li911  staff   103B Dec  7 18:41 .babelrc
-rw-rw-r--@ 1 li911  staff   146B Dec  3 02:28 .editorconfig
-rw-rw-r--@ 1 li911  staff    75B Dec  3 02:28 .gitignore
drwxr-xr-x@ 3 li911  staff    96B Dec  5 12:26 .mvn
-rwxr-xr-x@ 1 li911  staff   6.4K Sep 13 00:53 mvnw
-rw-rw-r--@ 1 li911  staff   5.0K Sep 13 00:53 mvnw.cmd
-rw-rw-r--@ 1 li911  staff   966B Dec  3 02:28 package.json
-rw-rw-r--@ 1 li911  staff   2.9K Dec  3 02:28 pom.xml
drwxrwxr-x@ 3 li911  staff    96B Dec  3 02:28 src
-rw-rw-r--@ 1 li911  staff   2.0K Dec  3 02:28 webpack.config.js
-rw-rw-r--@ 1 li911  staff   1.6K Dec  3 02:28 webpack.config.vendor.js
```
