### ISSUE TITLE
Unable to successfully generate OpenAPI Server from Spec file

### ISSUE THREAD

**Issue by InfoSec812** [pmlopes/vertx-starter#28]
When I try to generate a new Server project from my OpenAPI spec file, I get the linked errors:

https://imgur.com/a/8EcZqH9

The spec file can be found here: https://gist.github.com/InfoSec812/62b5784d79b4e36e536ae69b534eda43

**Comment by slinkydeveloper** [comment]
@InfoSec812 you provided an invalid openapi spec. In particular at line 15-16 `operationId` and `summary` must be inside an operation object, in this case under `option`. I tried to fix it and it works :smile: 

Unfortunately the actual library that we use for openapi loading doesn't validate the spec, but you can use https://mermade.org.uk/openapi-converter to validate the spec

**Comment by pmlopes** [comment]
Perhaps we should add a README: see #24

**Comment by InfoSec812** [comment]
I made the suggested change and ran it through the validation you suggested. The validation returned status `true`. I am still getting the same errors.

**Comment by slinkydeveloper** [comment]
@InfoSec812 That's pretty strange, I just tried both from cli and web and for me works. Have you tried to force webapp update removing the service worker? You should see Vertx-Starter v0.0.4 as page title

This is the result for me: [asd(1).zip](https://github.com/pmlopes/vertx-starter/files/2483121/asd.1.zip)

**Comment by InfoSec812** [comment]
@slinkydeveloper Slush Vert.x 0.0.4 is not available from NPM as far as I can see. I do see 0.0.4 on the vertx-starter web site though.

**Comment by InfoSec812** [comment]
@slinkydeveloper I tried that and I get:

```bash
$ create-vertx-app 
? Choose the build tool maven
? Project Name human-review
? Project Description (Optional) undefined
? Maven Group Id (Optional) gov.dhs.nppd
? Maven Artifact Id (Optional) human-review-backend
? Project Version (Optional) 1.0.0-SNAPSHOT
? (Experimental!) native image support (requires: GraalVM) No
? Choose your language java
? Choose the project type OpenAPI Server
? OpenAPI file (YAML or JSON) ./human-review-ui/openapi-v3.yml
? Choose your additional dependencies io.vertx:vertx-service-proxy, io.vertx:vertx-reactive-streams, io.vertx:vertx-rx-java2, io.vertx:vertx-sockjs-service-proxy, io.vertx:vertx-circuit-brea
ker, io.vertx:vertx-codegen, io.vertx:vertx-infinispan, io.vertx:vertx-config, io.vertx:vertx-config-kubernetes-configmap, io.vertx:vertx-service-proxy:processor, org.postgresql:postgresql
Cannot read property 'map' of undefined
TypeError: Cannot read property 'map' of undefined
    at getOperations (/usr/lib/node_modules/create-vertx-app/src/openapi/OpenAPIUtils.js:42:77)
    at Object.buildOpenAPIBaseMetadata (/usr/lib/node_modules/create-vertx-app/src/openapi/OpenAPIUtils.js:82:24)
    at generate (/usr/lib/node_modules/create-vertx-app/src/generators/OpenAPI_Server.js:20:43)
    at Promise.all.then.p (/usr/lib/node_modules/create-vertx-app/src/engine.js:132:16)
    at <anonymous>
```

**Comment by slinkydeveloper** [comment]
I can't reproduce the bug, but following your log I found a possible bug. #29 should fix it, can you try to clone and test locally?

**Comment by InfoSec812** [comment]
This is resolved in newer version. Closing
