### ISSUE TITLE
Creating New Maven Project using `web-api-service` dependency uses wrong version

### ISSUE THREAD

**Issue by InfoSec812** [pmlopes/vertx-starter#42]
All of the other Vert.x dependencies were added to the POM using version 3.6.2, but the `vertx-web-api-service` was imported with version `3.5.4` instead.

Perhaps a better solution would be to set a `<vertx.version>[VERSION]</vertx.version>` property in the POM and use that property throughout:

For example, instead of :
```
    <dependency>
      <groupId>io.vertx</groupId>
      <artifactId>vertx-web-api-service</artifactId>
      <version>3.5.4</version>
      <classifier>processor</classifier>
    </dependency>
```

Use:

```
    <dependency>
      <groupId>io.vertx</groupId>
      <artifactId>vertx-web-api-service</artifactId>
      <version>${vertx.version}</version>
      <classifier>processor</classifier>
    </dependency>
```

**Comment by pmlopes** [comment]
Generator now uses a BOM
